# Generated by Django 2.2.6 on 2019-10-15 15:31

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('avatar', models.ImageField(upload_to=employees.models.Employees._upload_files)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
    ]
