# Generated by Django 2.2.6 on 2019-10-15 15:33

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='avatar',
            field=models.ImageField(upload_to=employees.models.Employees._upload_avatar),
        ),
        migrations.AlterField(
            model_name='employees',
            name='cv',
            field=models.FileField(upload_to=employees.models.Employees._upload_files),
        ),
    ]
